### ISSUE TITLE
Error when exporting reports

### ISSUE THREAD

**Issue by arnupretorius** [samapriya/plantpy#1]
Hi there,

Thanks for the tool. Seems very useful! :)

However, when following your example, i.e. `!plantpy locust --start "2020-04-20" --end "2020-05-12" --country "ethiopia" --report "/content/tmp/report.csv"`, I get the following error:

`Writing report to : /content/tmp/report.csv
Traceback (most recent call last):
  File "/usr/local/bin/plantpy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/plantpy/plantpy.py", line 413, in main
    func(args)
  File "/usr/local/lib/python3.7/dist-packages/plantpy/plantpy.py", line 260, in locust_from_parser
    locust(start=args.start, end=args.end, country=args.country, report=args.report)
  File "/usr/local/lib/python3.7/dist-packages/plantpy/plantpy.py", line 246, in locust
    df = pd.read_csv(report, encoding="utf8")
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 2`

Which seems to be related to this issue here: https://stackoverflow.com/questions/18039057/python-pandas-error-tokenizing-data

Have you come across this before?

**Comment by arnupretorius** [comment]
So it seems inside the csv report file the request is sending back an HTML page with a 404 error: `<title>The page you were looking for doesn't exist (404)</title>`.
